/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import preenchendo.*;

/**
 *
 * @author Piu
 */
public class cadastro extends javax.swing.JFrame {

    classecadastromaior cadma = new classecadastromaior();
    classecadastromenor cadme = new classecadastromenor();

    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botsalcad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titunome = new javax.swing.JLabel();
        camponomealuno = new javax.swing.JTextField();
        titucpf = new javax.swing.JLabel();
        titurg = new javax.swing.JLabel();
        titunasc = new javax.swing.JLabel();
        tituender = new javax.swing.JLabel();
        campoenderealuno = new javax.swing.JTextField();
        titutel = new javax.swing.JLabel();
        titudatacadas = new javax.swing.JLabel();
        titunomecurso = new javax.swing.JLabel();
        camponomecursoaluno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numnivaluno = new javax.swing.JFormattedTextField();
        campocpfaluno = new javax.swing.JFormattedTextField();
        camporgaluno = new javax.swing.JFormattedTextField();
        campotelaluno = new javax.swing.JFormattedTextField();
        campodatacadastaluno = new javax.swing.JFormattedTextField();
        camponascialuno = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        titunomeresp = new javax.swing.JLabel();
        camponomeresp = new javax.swing.JTextField();
        titucpfresp = new javax.swing.JLabel();
        titurgresp = new javax.swing.JLabel();
        titutelresp = new javax.swing.JLabel();
        marcaraddrespons = new javax.swing.JCheckBox();
        campocpfresp = new javax.swing.JFormattedTextField();
        camporgresp = new javax.swing.JFormattedTextField();
        campotelresp = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        botsalcad.setText("Salvar");
        botsalcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalcadActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS DO ALUNO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        titunome.setText("Nome completo:");

        camponomealuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomealunoActionPerformed(evt);
            }
        });

        titucpf.setText("CPF:");

        titurg.setText("RG:");

        titunasc.setText("Data de nascimento:");

        tituender.setText("Endereço completo:");

        campoenderealuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoenderealunoActionPerformed(evt);
            }
        });

        titutel.setText("Telefone:");

        titudatacadas.setText("Data de cadastro:");

        titunomecurso.setText("Curso:");

        camponomecursoaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomecursoalunoActionPerformed(evt);
            }
        });

        jLabel11.setText("Número de níveis:");

        numnivaluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        numnivaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numnivalunoActionPerformed(evt);
            }
        });

        try {
            campocpfaluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campocpfaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocpfalunoActionPerformed(evt);
            }
        });

        try {
            camporgaluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        camporgaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camporgalunoActionPerformed(evt);
            }
        });

        try {
            campotelaluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campotelaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotelalunoActionPerformed(evt);
            }
        });

        campodatacadastaluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campodatacadastaluno.setText("  /  /    ");
        campodatacadastaluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campodatacadastalunoActionPerformed(evt);
            }
        });

        camponascialuno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        camponascialuno.setText("  /  /    ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(titunome)
                    .addComponent(camponomealuno, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titunasc)
                    .addComponent(campoenderealuno, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titucpf)
                            .addComponent(campocpfaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titurg)
                            .addComponent(camporgaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(titutel)
                    .addComponent(titunomecurso)
                    .addComponent(camponomecursoaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numnivaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campotelaluno, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titudatacadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campodatacadastaluno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituender)
                    .addComponent(camponascialuno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titunome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camponomealuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titucpf)
                    .addComponent(titurg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campocpfaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(camporgaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titunasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camponascialuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoenderealuno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titutel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campotelaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titudatacadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campodatacadastaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titunomecurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camponomecursoaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numnivaluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS DO RESPONSÁVEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        titunomeresp.setText("Nome:");

        camponomeresp.setEditable(false);
        camponomeresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camponomerespActionPerformed(evt);
            }
        });

        titucpfresp.setText("CPF:");

        titurgresp.setText("RG:");

        titutelresp.setText("Telefone:");

        marcaraddrespons.setText("Adicionar responsável");
        marcaraddrespons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaraddresponsActionPerformed(evt);
            }
        });

        campocpfresp.setEditable(false);
        try {
            campocpfresp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campocpfresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocpfrespActionPerformed(evt);
            }
        });

        camporgresp.setEditable(false);
        try {
            camporgresp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        camporgresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camporgrespActionPerformed(evt);
            }
        });

        campotelresp.setEditable(false);
        try {
            campotelresp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campotelresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campotelrespActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marcaraddrespons)
                    .addComponent(titucpfresp)
                    .addComponent(camponomeresp, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titurgresp)
                    .addComponent(titutelresp)
                    .addComponent(titunomeresp)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(camporgresp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campocpfresp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                    .addComponent(campotelresp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(marcaraddrespons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titunomeresp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camponomeresp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titucpfresp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campocpfresp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titurgresp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(camporgresp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titutelresp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campotelresp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botsalcad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botsalcad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void camponomerespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomerespActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_camponomerespActionPerformed

    private void marcaraddresponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaraddresponsActionPerformed
        
        if(marcaraddrespons.isSelected()){
        camponomeresp.setEditable(true);
        campocpfresp.setEditable(true);
        camporgresp.setEditable(true);
        campotelresp.setEditable(true);
        }else{
        marcaraddrespons.setSelected(false);
        camponomeresp.setEditable(false);
        campocpfresp.setEditable(false);
        camporgresp.setEditable(false);
        campotelresp.setEditable(false); 
        }
        
    }//GEN-LAST:event_marcaraddresponsActionPerformed

    private void camponomealunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomealunoActionPerformed
        // TODO add your handling code here:
        
            
        
    }//GEN-LAST:event_camponomealunoActionPerformed

    private void botsalcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalcadActionPerformed
        // TODO add your handling code here:
        String anul = "";
        
        if (validardados())
        {
            if(incluircampo())
            {
                
              cadma.inseriraluno();
              cadme.inseriresp();
            
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            
            }
        }
        
             camponomealuno.setText(String.valueOf(anul));
             campocpfaluno.setText(String.valueOf(anul));
             camporgaluno.setText(String.valueOf(anul));
             camponascialuno.setText(String.valueOf(anul));
             campoenderealuno.setText(String.valueOf(anul));
             campotelaluno.setText(String.valueOf(anul));
             campodatacadastaluno.setText(String.valueOf(anul));
             camponomecursoaluno.setText(String.valueOf(anul));
             numnivaluno.setText(String.valueOf(anul));
             camponomeresp.setText(String.valueOf(anul));
             campocpfresp.setText(String.valueOf(anul));
             camporgresp.setText(String.valueOf(anul));
             campotelresp.setText(String.valueOf(anul));          
        
       

    }//GEN-LAST:event_botsalcadActionPerformed

    private void campoenderealunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoenderealunoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoenderealunoActionPerformed

    private void camponomecursoalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camponomecursoalunoActionPerformed
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_camponomecursoalunoActionPerformed

    private void numnivalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numnivalunoActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_numnivalunoActionPerformed

    private void campocpfalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocpfalunoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campocpfalunoActionPerformed

    private void camporgalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camporgalunoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_camporgalunoActionPerformed

    private void campodatacadastalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campodatacadastalunoActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_campodatacadastalunoActionPerformed

    private void campotelalunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotelalunoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campotelalunoActionPerformed

    private void campocpfrespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocpfrespActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_campocpfrespActionPerformed

    private void camporgrespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camporgrespActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_camporgrespActionPerformed

    private void campotelrespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campotelrespActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campotelrespActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cadastro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botsalcad;
    private javax.swing.JFormattedTextField campocpfaluno;
    private javax.swing.JFormattedTextField campocpfresp;
    private javax.swing.JFormattedTextField campodatacadastaluno;
    private javax.swing.JTextField campoenderealuno;
    private javax.swing.JFormattedTextField camponascialuno;
    private javax.swing.JTextField camponomealuno;
    private javax.swing.JTextField camponomecursoaluno;
    private javax.swing.JTextField camponomeresp;
    private javax.swing.JFormattedTextField camporgaluno;
    private javax.swing.JFormattedTextField camporgresp;
    private javax.swing.JFormattedTextField campotelaluno;
    private javax.swing.JFormattedTextField campotelresp;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox marcaraddrespons;
    private javax.swing.JFormattedTextField numnivaluno;
    private javax.swing.JLabel titucpf;
    private javax.swing.JLabel titucpfresp;
    private javax.swing.JLabel titudatacadas;
    private javax.swing.JLabel tituender;
    private javax.swing.JLabel titunasc;
    private javax.swing.JLabel titunome;
    private javax.swing.JLabel titunomecurso;
    private javax.swing.JLabel titunomeresp;
    private javax.swing.JLabel titurg;
    private javax.swing.JLabel titurgresp;
    private javax.swing.JLabel titutel;
    private javax.swing.JLabel titutelresp;
    // End of variables declaration//GEN-END:variables

    public boolean validardados ()
    {
           if(camponomealuno.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Nome' do aluno!");
            camponomealuno.requestFocus();
            return false;
        }
          if(campocpfaluno.getText().equals("   .   .   -  "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'CPF' do aluno!");
            campocpfaluno.requestFocus();
            return false;
        }
           if(camporgaluno.getText().equals("  .   .   -  "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'RG' do aluno!");
            camporgaluno.requestFocus();
            return false;
        }
            if(camponascialuno.getText().equals("  /  /    "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Data de Nascimento' do aluno!");
            camponascialuno.requestFocus();
            return false;
        }
            if(campoenderealuno.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Endereço' do aluno!");
            campoenderealuno.requestFocus();
            return false;
        }
            if(campotelaluno.getText().equals("     -    "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Telefone' do aluno!");
            campotelaluno.requestFocus();
            return false;
        }
            if(campodatacadastaluno.getText().equals("  /  /    "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Data de cadastro' do aluno!");
            campodatacadastaluno.requestFocus();
            return false;
        }
            if(camponomecursoaluno.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Curso' do aluno!");
            camponomecursoaluno.requestFocus();
            return false;
        }
            if(numnivaluno.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Número de níveis' do aluno!");
            numnivaluno.requestFocus();
            return false;
        }
                       
        if(marcaraddrespons.isSelected()){
          
           if(camponomeresp.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Nome' do responsável!");
            camponomeresp.requestFocus();
            return false;
        } 
            if(campocpfresp.getText().equals("   .   .   -  "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'CPF' do responsável!");
            campocpfresp.requestFocus();
            return false;
        }
            if(camporgresp.getText().equals("  .   .   -  "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'RG' do responsável!");
            camporgresp.requestFocus();
            return false;
        } 
           
            if(campotelresp.getText().equals("     -    "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Telefone' do responsável!");
            campotelresp.requestFocus();
            return false;
        } 
        
        }      
                return true;
    }
    
    
        public boolean incluircampo(){  
            try{
         String n = camponomealuno.getText();      
            cadma.setNome_est(n);
            cadme.setNome_resp(camponomeresp.getText()); 
         int c = (Integer.parseInt(campocpfaluno.getText().replace(".", "").replace("-", "")));
            cadma.setCpf_est(c);
            cadme.setCpf_resp((Integer.parseInt(campocpfresp.getText().replace(".", "").replace("-", ""))));   
         int r = (Integer.parseInt(camporgaluno.getText().replace(".", "").replace("-", "")));
            cadma.setRg_est(r);
            cadme.setRg_resp((Integer.parseInt(camporgresp.getText().replace(".", "").replace("-", ""))));
         String dn = camponascialuno.getText();
            cadma.setData_nasc_est(dn);
         String e = campoenderealuno.getText();
            cadma.setEnder_est(e);
        int f = (Integer.parseInt(campotelaluno.getText().replace("-", "")));
            cadma.setFone_est(f);
            cadme.setFone_resp((Integer.parseInt(campotelresp.getText().replace("-", ""))));
         String dc = campodatacadastaluno.getText();
            cadma.setData_cadas(dc);
         String cu = camponomecursoaluno.getText();
            cadma.setCurso_est(cu);  
        int ni = Integer.parseInt(numnivaluno.getText());
            cadma.setNiveis_est(ni);
        
            JOptionPane.showMessageDialog(null, "Dado final:" +"Data nas " +dn +"\n"
                +"Data cadas "+dc +"\n" +n +"\n" +c +"\n" +r +"\n"
                +e +"\n" +f +"\n" +cu +"\n" +ni);
        
        
            } catch (Exception e) 
            {  
              System.out.println("Não foi");
              System.out.println(e);
              
              System.exit(0); 

             }
            return true;
        }
    
    
    
    


}
