/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import javax.swing.JOptionPane;
import preenchendo.*;
import java.math.BigDecimal;
import java.text.DecimalFormat;

/**
 *
 * @author Piu
 */
public class chamada extends javax.swing.JFrame {
    
    classechamada cham = new classechamada();
    
    
    public chamada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campodata = new javax.swing.JFormattedTextField();
        titudata = new javax.swing.JLabel();
        campocodalu = new javax.swing.JTextField();
        titucodalu = new javax.swing.JLabel();
        titufalta = new javax.swing.JLabel();
        botsalcham = new javax.swing.JButton();
        campofaltas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        campodata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        campodata.setText("");
        campodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campodataActionPerformed(evt);
            }
        });
        campodata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campodataKeyPressed(evt);
            }
        });

        titudata.setText("Data");

        campocodalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campocodaluActionPerformed(evt);
            }
        });

        titucodalu.setText("Código do aluno");

        titufalta.setText("Faltas");

        botsalcham.setText("Salvar");
        botsalcham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalchamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(titucodalu)
                            .addGap(13, 13, 13))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(titudata)
                            .addGap(18, 18, 18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titufalta)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campocodalu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campofaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campodata, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botsalcham)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titudata))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campocodalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titucodalu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titufalta)
                    .addComponent(campofaltas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(botsalcham)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campocodaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campocodaluActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campocodaluActionPerformed

    private void botsalchamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalchamActionPerformed
        // TODO add your handling code here: 
        String anul = "";
        if(validardados())
        {
            if(incluircampo())  
            {
                cham.inserirchamada();
                JOptionPane.showMessageDialog(this, "Sucesso!");
            }
        }
        
        
        campodata.setText(String.valueOf(anul));
        campocodalu.setText(String.valueOf(anul));
        campofaltas.setText(String.valueOf(anul));
              
    }//GEN-LAST:event_botsalchamActionPerformed

    private void campodataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campodataKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_campodataKeyPressed

    private void campodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campodataActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_campodataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chamada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botsalcham;
    private javax.swing.JTextField campocodalu;
    private javax.swing.JFormattedTextField campodata;
    private javax.swing.JTextField campofaltas;
    private javax.swing.JLabel titucodalu;
    private javax.swing.JLabel titudata;
    private javax.swing.JLabel titufalta;
    // End of variables declaration//GEN-END:variables

 public boolean validardados ()
    {
        if(campodata.getText().equals("  /  /    "))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Data'!");
            campodata.requestFocus();
            return false;
        }
        
        if(campocodalu.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Código do aluno'!");
            campocodalu.requestFocus();
            return false;
        }
        if(campofaltas.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Faltas'!");
            campofaltas.requestFocus();
            return false;
        }
        return true;
    }
        
        public boolean incluircampo()
        {
            try{
            cham.setData_cham(campodata.getText()); 
            cham.setCod_est(Integer.parseInt(campocodalu.getText()));        
            cham.setFrequenc_cham(Integer.parseInt(campofaltas.getText())); 
            }   catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao incluir chamada");
            System.out.println(e);
            System.exit(0); 
        }
        return true;
        }
        
        


}
