/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import preenchendo.*;

/**
 *
 * @author Piu
 */
public class notas extends javax.swing.JFrame {

    classenotas nota = new classenotas();
    
    public notas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titunomenota = new javax.swing.JLabel();
        titunivelcursonota = new javax.swing.JLabel();
        titunotateste = new javax.swing.JLabel();
        titunotaprova = new javax.swing.JLabel();
        campocodalu = new javax.swing.JTextField();
        camponivelcur = new javax.swing.JTextField();
        campomedia = new javax.swing.JTextField();
        botsalnot = new javax.swing.JButton();
        butmedia = new javax.swing.JButton();
        camponotaprova = new javax.swing.JTextField();
        camponotateste = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titunomenota.setText("Código do aluno:");

        titunivelcursonota.setText("Nível do curso:");

        titunotateste.setText("Nota do teste:");

        titunotaprova.setText("Nota da prova:");

        campomedia.setEditable(false);
        campomedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campomediaActionPerformed(evt);
            }
        });

        botsalnot.setText("Salvar");
        botsalnot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botsalnotActionPerformed(evt);
            }
        });

        butmedia.setText("Média");
        butmedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butmediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titunotaprova)
                                    .addComponent(titunotateste)
                                    .addComponent(titunivelcursonota)
                                    .addComponent(titunomenota)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(butmedia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(camponivelcur, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(campocodalu)
                            .addComponent(campomedia)
                            .addComponent(camponotaprova)
                            .addComponent(camponotateste)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(botsalnot)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titunomenota)
                    .addComponent(campocodalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(camponivelcur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titunivelcursonota))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titunotateste)
                    .addComponent(camponotateste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titunotaprova)
                    .addComponent(camponotaprova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campomedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butmedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(botsalnot)
                .addGap(33, 33, 33))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botsalnotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botsalnotActionPerformed
        // TODO add your handling code here:
        String anul = "";
        if(validardados())
        {
            if(incluircampo())  
            {
                nota.inserirnotas();
                JOptionPane.showMessageDialog(this, "Sucesso!");
            }
        }
          
        
        campocodalu.setText(String.valueOf(anul));
        camponivelcur.setText(String.valueOf(anul));
        camponotateste.setText(String.valueOf(anul));
        camponotaprova.setText(String.valueOf(anul));
        campomedia.setText(String.valueOf(anul));

        
    }//GEN-LAST:event_botsalnotActionPerformed

    private void campomediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campomediaActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_campomediaActionPerformed

    private void butmediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butmediaActionPerformed
        // TODO add your handling code here:
        if(incluircampo()){
       String m = nota.executeStoredProcedure();
       nota.setMedia_descri_not(m);
        
        campomedia.setText(nota.getMedia_descri_not());
        }
    }//GEN-LAST:event_butmediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(notas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new notas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botsalnot;
    private javax.swing.JButton butmedia;
    private javax.swing.JTextField campocodalu;
    private javax.swing.JTextField campomedia;
    private javax.swing.JTextField camponivelcur;
    private javax.swing.JTextField camponotaprova;
    private javax.swing.JTextField camponotateste;
    private javax.swing.JLabel titunivelcursonota;
    private javax.swing.JLabel titunomenota;
    private javax.swing.JLabel titunotaprova;
    private javax.swing.JLabel titunotateste;
    // End of variables declaration//GEN-END:variables

     public boolean validardados ()
    {
        if(campocodalu.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Código do aluno'!");
            campocodalu.requestFocus();
            return false;
        }
        if(camponivelcur.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Nível do curso'!");
            camponivelcur.requestFocus();
            return false;
        }
        if(camponotateste.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Nota do teste'!");
            camponotateste.requestFocus();
            return false;
        }
        if(camponotaprova.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Preencha o campo 'Nota da prova'!");
            camponotaprova.requestFocus();
            return false;
        }
        
        return true;
    }
     
     
     public boolean incluircampo()
        {
            try{
        nota.setCod_est(Integer.parseInt(campocodalu.getText())); 
        nota.setNivel_not(Integer.parseInt(camponivelcur.getText()));
        nota.setNota_test_not(Double.parseDouble(camponotateste.getText()));
        nota.setNota_prov_not(Double.parseDouble(camponotaprova.getText()));  
        
       
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao incluir notas");
            System.out.println(e);
            System.exit(0); 
            }
            
          return true;   
        }
     
     
}
